service: aws-csharp2-0

provider:
  name: aws
  runtime: dotnetcore2.0
  region: ap-southeast-2

package:
  artifact: bin/release/netcoreapp2.0/publish/deploy-package.zip

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    events:
      - http:
          path: /
          method: get
