service: gcp-go111

provider:
  name: google
  memorySize: 1024
  runtime: go111
  project: serverless-cloud-benchmark
  credentials: ~/.gcloud/benchmark.json # path must be absolute

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  gcp-go111-hello:
    handler: hello
    events:
      - http: /hello
  gcp-go111-users:
    handler: users
    events:
      - http: /users

#resources:
#  resources:
#    - type: storage.v1.bucket
#      name: my-serverless-service-bucket
#  imports:
#    - path: my_template.jinja