version: 2.1

executors: 
  ubuntu:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

commands:
  build:
    parameters:
      provider: 
        type: string
        default: "aws"
      runtime:
        type: string
        default: ""
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/<< parameters.provider >>/<< parameters.runtime >>
      - run:
          name: Build and Package
          working_directory: ~/project/<< parameters.provider >>/<< parameters.runtime >>
          command: make build package
      - persist_to_workspace:
          root: ~/project/<< parameters.provider >>/<< parameters.runtime >>
          paths: .serverless
  deployer:
    # branches:
    #   only:
    #     - master
    parameters:
      provider: 
        type: string
        default: "aws"
      runtime:
        type: string
        default: ""
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/<< parameters.provider >>/<< parameters.runtime >>
      - deploy:
          name: Deploy
          command: make deploy
          working_directory: ~/project/<< parameters.provider >>/<< parameters.runtime >>

jobs:
  # Build Jobs
  build-aws-csharp2-1:
    executor: ubuntu 
    steps:
      - build:
          provider: aws
          runtime: aws-csharp2.1
  build-aws-fsharp2-1:
    executor: ubuntu 
    steps:
      - build:
          provider: aws
          runtime: aws-fsharp2.1
  build-aws-go1-x:
    executor: ubuntu 
    steps:
      - build:
          provider: aws
          runtime: aws-go1.x
  build-aws-java8:
    executor: ubuntu 
    steps:
      - build:
          provider: aws
          runtime: aws-java8
  build-aws-nodejs8-10:
    executor: ubuntu 
    steps:
      - build:
          provider: aws
          runtime: aws-nodejs8.10
  build-aws-python3-7:
    executor: ubuntu 
    steps:
      - build:
          provider: aws
          runtime: aws-python3.7
  build-aws-ruby2-5:
    executor: ubuntu 
    steps:
      - build:
          provider: aws
          runtime: aws-ruby2.5

  # Deploy Jobs
  deploy-aws-csharp2-1:
    executor: ubuntu 
    steps:
      - deployer:
          provider: aws
          runtime: aws-csharp2.1
  deploy-aws-fsharp2-1:
    executor: ubuntu 
    steps:
      - deployer:
          provider: aws
          runtime: aws-fsharp2.1
  deploy-aws-go1-x:
    executor: ubuntu 
    steps:
      - deployer:
          provider: aws
          runtime: aws-go1.x
  deploy-aws-java8:
    executor: ubuntu 
    steps:
      - deployer:
          provider: aws
          runtime: aws-java8
  deploy-aws-nodejs8-10:
    executor: ubuntu 
    steps:
      - deployer:
          provider: aws
          runtime: aws-nodejs8.10
  deploy-aws-python3-7:
    executor: ubuntu 
    steps:
      - deployer:
          provider: aws
          runtime: aws-python3.7
  deploy-aws-ruby2-5:
    executor: ubuntu 
    steps:
      - deployer:
          provider: aws
          runtime: aws-ruby2.5



workflows:
  version: 2
  build-deploy-aws:
    jobs:
      - build-aws-csharp2-1
      - build-aws-fsharp2-1
      - build-aws-go1-x
      - build-aws-java8
      - build-aws-nodejs8-10
      - build-aws-python3-7
      - build-aws-ruby2-5
      - deploy-aws-csharp2-1:
          requires: 
            - build-aws-csharp2-1
      - deploy-aws-fsharp2-1:
          requires: 
            - build-aws-fsharp2-1
      - deploy-aws-go-1-x:
          requires: 
            - build-aws-go1-x

