version: 2.1
executors:
  aws-executor:
    machine: 
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
  gcp-executor:
    machine: 
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
jobs:
  build-gcp:
    executor: gcp-executor
    steps:
      - checkout
      - run:
          name: google-nodejs8
          command: make package
          environment:
            RUNTIMES: google-nodejs8
  build-aws:
    parameters:
      runtime:
        type: string
        default: ""
    executor: aws-executor
    steps:
      - checkout
      - run:
          name: << parameters.runtime >>
          command: make package
          working_directory: ~/project/aws/<< parameters.runtime >>
      - persist_to_workspace:
        root: ~/project/aws/
        paths:
          - << parameters.runtime >>/.serverless
  deploy-aws:
    executor: aws-executor
    parameters:
      runtime:
        type: string
        default: ""
    steps:
      - checkout
      - attach_workspace:
        at: ~/project/aws/
      - deploy:
          name: << parameters.runtime >>
          command: make deploy
          working_directory: ~/project/aws/<< parameters.runtime >>
workflows:
  version: 2
  build-deploy-aws:
    jobs:
      - build-aws:
          name: build-aws-csharp2.1
          runtime: aws-csharp2.1
      - build-aws:
          name: build-aws-fsharp2.1
          runtime: aws-csharp2.1
      - build-aws:
          name: build-aws-go1.x
          runtime: aws-go1.x
      - build-aws:
          name: build-aws-java8
          runtime: aws-java8
      - build-aws:
          name: build-aws-nodejs8.10
          runtime: aws-nodejs8.10
      - build-aws:
          name: build-aws-python3.7
          runtime: aws-python3.7
      - build-aws:
          name: build-aws-ruby2.5
          runtime: aws-ruby2.5

      - deploy-aws:
          name: deploy-aws-csharp2.1
          runtime: aws-csharp2.1
          requires: 
            - build-aws-csharp2.1
          filters:
            branches:
              only:
                - master
      - deploy-aws:
          name: deploy-aws-go1.x
          runtime: aws-go1.x
          requires: 
            - build-aws-go1.x
          filters:
            branches:
              only:
                - master