version: 2.1
executors:
  aws-executor:
    machine: 
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

jobs:
  build-aws:
    executor: aws-executor
    parallelism: 2
    steps:
      - checkout
      - run:
          name: aws-chsharp2.1
          working_directory: ~/project/aws
          command: make package
          environment:
            RUNTIME: aws-chsharp2.1
      - run:
          name: aws-go1.x
          working_directory: ~/project/aws
          command: make package
          environment:
            RUNTIME: aws-go1.x
  deploy-aws:
    executor: aws-executor
    parallelism: 2
    steps:
      - run:
          name: aws-chsharp2.1
          working_directory: ~/project/aws
          command: make deploy
          environment:
            RUNTIME: aws-chsharp2.1
workflows:
  version: 2
  build-deploy-aws:
    jobs:
      - build-aws
      - deploy-aws:
          require: 
            - build-aws
          filters:
            branches:
              only:
                - master