version: 2
jobs:
  build:
    docker:
      - image: flemay/musketeers

    steps:
      - checkout

      - run:
          name: Greeting
          command: make

      - run:
          name: Print the Current Time
          command: date