version: 2.1
executors:
  aws-executor:
    machine: 
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
  gcp-executor:
    machine: 
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

commands:
  package:
    parameters:
      runtime:
        type: string
        default: ""
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/aws/<< parameters.runtime >>
      - run:
          name: << parameters.runtime >>
          command: make package
          working_directory: ~/project/aws/<< parameters.runtime >>
      - persist_to_workspace:
        root: .
        paths: .serverless



jobs:
  pack-aws-go1.x:
    executor: aws-executor
    steps:
      - package:
          runtime: aws-csharp2.1
  deploy:
    parameters:
      runtime:
        type: string
        default: ""
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/aws/<< parameters.runtime >>
      - deploy:
          name: << parameters.runtime >>
          command: make package
          working_directory: ~/project/aws/<< parameters.runtime >>

workflows:
  version: 2
  build-deploy-aws:
    jobs:
      - package-aws-go1.x
          # name: build-aws-csharp2.1
          # runtime: aws-csharp2.1
      # - build-aws:
      #     name: build-aws-fsharp2.1
      #     runtime: aws-csharp2.1
      # - build-aws:
      #     name: build-aws-go1.x
      #     runtime: aws-go1.x
      # - build-aws:
      #     name: build-aws-java8
      #     runtime: aws-java8
      # - build-aws:
      #     name: build-aws-nodejs8.10
      #     runtime: aws-nodejs8.10
      # - build-aws:
      #     name: build-aws-python3.7
      #     runtime: aws-python3.7
      # - build-aws:
      #     name: build-aws-ruby2.5
      #     runtime: aws-ruby2.5
      # - deploy-aws:
      #     name: deploy-aws-csharp2.1
      #     runtime: aws-csharp2.1
      #     requires: 
      #       - package-aws-csharp2.1
      #     filters:
      #       branches:
      #         only:
      #           - master
      - deploy-aws:
          name: deploy-aws-go1.x
          runtime: aws-go1.x
          requires: 
            - package-aws-go1.x
          filters:
            branches:
              only:
                - master