version: 2.1
executors:
  aws-executor:
    machine: 
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
  gcp-executor:
    machine: 
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
jobs:
  build-gcp:
    executor: gcp-executor
    working_directory: ~/project/google
    steps:
      - checkout
      - run:
          name: google-nodejs8
          command: make package
          environment:
            RUNTIMES: google-nodejs8
  build-aws:
    parameters:
      runtime:
        type: string
        default: ""
    executor: aws-executor
    working_directory: ~/project/aws
    steps:
      - checkout
      - run:
          name: << parameters.runtime >>
          command: make package
          environment:
            RUNTIMES: << parameters.runtime >>
    # persist_to_workspace:
    #   root: ~/project/aws/<< parameters.runtime >>
    #   paths:
    #     - .serverless
  deploy-aws:
    executor: aws-executor
    parameters:
      runtime:
        type: string
        default: ""
    steps:
      - checkout
      - deploy:
          name: << parameters.runtime >>
          working_directory: ~/project/aws
          command: make deploy
          environment:
            RUNTIME: << parameters.runtime >>
workflows:
  version: 2
  build-deploy-aws:
    jobs:
      - build-aws:
          name: build-aws-csharp2.1
          runtime: aws-csharp2.1
      - build-aws:
          name: build-aws-go1.x
          runtime: aws-go1.x
      - deploy-aws:
          name: deploy-aws-csharp2.1
          runtime: aws-csharp2.1
      # - deploy-aws:
      #     requires: 
      #       - build-aws
      #     filters:
      #       branches:
      #         only:
      #           - master