version: 2
jobs:
  build:
    docker:
      - image: flemay/musketeers

    steps:
      - checkout
      - run:
          name: package
          command: make package
          environment:
            PROVIDERS: aws