service: aws-fsharp2-0

provider:
  name: aws
  runtime: dotnetcore2.0

package:
  artifact: bin/release/netcoreapp2.0/publish/deploy-package.zip

functions:
  hello:
    handler: FsharpHandlers::AwsDotnetFsharp.Handler::hello
    events:
      - http:
          path: /
          method: get