org: serverlesscloud
app: multi-cloud-benchmark
service: gcp-nodejs10

provider:
  name: google
  memorySize: 1024
  runtime: nodejs10
  region: us-east4
  project: serverless-cloud-benchmarks
  credentials: ~/.gcloud/serverless-cloud-benchmarks.json # path must be absolute

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  gcp-nodejs10-hello:
    handler: hello
    events:
      - http: /hello
  gcp-nodejs10-users:
    handler: users
    events:
      - http: /users
